### PR TITLE
Making name and subject field values links to searches.

### LINKED ISSUE #140: Controlled headings should be links
Subjects and Names

### PR DESCRIPTION
**Pull request by escowles**
Fixes #140

### CODE REVIEW

**Comment by tpendragon** [comment]
Is there a relatively simple way to do this as a part of the presenter?

**Comment by tampakis** [comment]
Rather than overriding the show_default partial, you can configure links to a search in the catalog controller.
https://github.com/pulibrary/cicognara-rails/blob/master/app/controllers/catalog_controller.rb#L98

i.e:
```
    config.add_show_field 'author_display', label: 'Author', link_to_search: true
```

**Comment by tpendragon** [comment]
Oh, that's even better.

**Comment by escowles** [comment]
Thanks for the help @tampakis — much nicer to just add the `link_to_search` option!

**Pull request merged**
