### PR TITLE
add item* to .gitignore

### PR DESCRIPTION
**Pull request by jpstroop**

### CODE REVIEW

**Comment by cwulfman** [comment]
Why are there edited item*.html files in this commit? I thought we were removing all the partials from the repo.

**Comment by tampakis** [comment]
The item fixture partials accidentally slipped in in a past commit. I took care of this in this branch: https://github.com/pulibrary/cicognara-rails/tree/render_items

**Comment by jpstroop** [comment]
Oh OK. They were already in the repo when I made this change, I thought you wanted them there as test fixtures or something

**Comment by tampakis** [comment]
blame @tampakis https://github.com/pulibrary/cicognara-rails/pull/103

**Pull request closed without merging**
