### PR TITLE
Add spec/support/stub_blacklight_views

### PR DESCRIPTION
**Pull request by hackmastera**
Requires updating rspec to use newer `without_partial_double_verification`

Most co-authors ever.

### CODE REVIEW

**Comment by tpendragon** [comment]
CI is failing because it's using Bundler 1

**Comment by hackmastera** [comment]
@tpendragon I just updated circlci in #408 what are your thoughts on that / that pr?

**Comment by tpendragon** [comment]
Oh yup! Looks good, merged

**Comment by hackmastera** [comment]
@tpendragon okay this should be ready now

**Pull request merged**
