### PR TITLE
Add Mirador viewer in place of UV.

### PR DESCRIPTION
**Pull request by tpendragon**
Won't work for MVWs at all, but something to look at.

### CODE REVIEW

**Comment by escowles** [comment]
I deployed this to staging, and linked manifests for an Entry where we have both Microfiche and Princeton scans: http://libruby-dev.princeton.edu/cicognara/catalog/843

**Comment by tpendragon** [comment]
@escowles The second manifest you set isn't marked "Complete" in Figgy.

**Comment by escowles** [comment]
@tpendragon Oh, that would make it hard to display both of them.  I found an object with two *public* manifests, and it does work as expected:

screen shot 2018-07-11 at 1 08 32 pm

**Comment by tpendragon** [comment]
@escowles Yeah. Link: http://libruby-dev.princeton.edu/cicognara/catalog/3504

How do you feel about it? I'm not a fan, personally. I'm not sure default having two displaying side-by-side is super useful, and the table of contents seems to take up a lot of space. I guess this is pretty cool though:

screen shot 2018-07-11 at 10 20 51 am

**Comment by escowles** [comment]
@tpendragon Yes, I agree that the default display isn't great and the (sometimes worthless) table of contents takes up way more room than is reasonable.  But getting to that side-by-side display is nice.

Maybe we should leave UV, but have a button to load a full-screen Mirador viewer for the side-by-side view?

**Comment by tpendragon** [comment]
Another option, tabbed UV:

Tabbed UV

**Comment by tpendragon** [comment]
We're going to use a tabbed UV.

**Pull request closed without merging**
