### PR TITLE
[WIP] Initial UI adjustments

### LINKED ISSUE #108: Add top-level link to browse catalogo from home page

### LINKED ISSUE #111: make the current cicognara.org page the about page

### LINKED ISSUE #112: make a nice home page
with entry to a "browse" view and a search box

### LINKED ISSUE #113: Create link to browse and catalog view from search results

### LINKED ISSUE #117: Need a "news" page
@axamei maybe do w/ "about" page?

### LINKED ISSUE #122: Do the institution logos have to be in the footer of every page?
What should be in the footer?

### LINKED ISSUE #123: Add browse button to header?
Do we want to add "Browse the Catalogo" next to search box on all pages?

browse_catalogo

### LINKED ISSUE #125: Create logo
@jpstroop Would the text be "The Digital Cicognara Library" or "Digital Cicognara Library" or something else?

### PR DESCRIPTION
**Pull request by axamei**
add static pages. closes #117 
create link to browse and catalog view from search. closes #113 
make a nice homepage. closes #112 
add top level link to browse catalogo. closes #108 
make current cicognara page the about page. closes #111 
adjust footer styling. closes #122
add browse button to header. closes #123
include logo. closes #125

### CODE REVIEW

**Comment by jpstroop** [comment]
@axamei I can review after lunch if you're ready. Let me know.

**Comment by axamei** [comment]
@jpstroop There's more to be done re: look and feel, but this is a start. Please review when you can.

**Comment by jpstroop** [comment]
It's looking really good! I'm not sure what's still on your TODO list, so please ignore anything below that's obvious.

 * Maybe while you're working on the logo for maps.princeton.edu you could suggest one for this project as well? ;-)
 * I'm not sure that the `/about` content should be repeated on the home page--maybe you were planning to take that out? I think it gets confusing. And on the `/about` page, I wonder if there should be some kind of ToC, since there are three headings? I don't want it to look like Wikipedia or anything, but maybe some that's floated off to the right?
 * I'm seeing some weirdness when I use the back button. Probably turbolinks? That can be a separate ticket if you want.
 * In the search results and record show pages, I think the text from the TEI can be much larger:
    image
    and obviously the background coloring should go.
 * Somewhat related, the [browse screen](http://localhost:3000/catalogo/section_1.24/index.html#item_2170) just needs help...I suspect you haven't gotten there yet, but again, bigger font, and maybe the menu at the left should stay in a fixed position?
 * Finally, back on the static pages, I'm noticing that when the window is wider, the text block is narrower:
    image
    But when the window is narrower, it gets wider:
    image
    I think the width of the text block in the second image would be fine in all cases.

This is looking really great. Thanks!

**Comment by axamei** [comment]
@jpstroop When you can, please review. I need to clean up the code (please don't merge), but I think most issues we discussed are resolved with these new changes.

**Comment by jpstroop** [comment]
Will try to do mid-AM tomorrow. Thanks!!

**Comment by jpstroop** [comment]
@axamei This looks great!

Just one comment: I wonder if you have an opinion about the `h1` on the catalog show page:

image

i.e. "Catalogo Item 2745" in the above.

That's sort of a made up construction ("Catalogo Item") and I wonder there there's a way we could just make the TEI text, in this case:

> 2745. BARTOLI Pietro Santi, Musaeum Odescalcum, sive thesaurus antiquarium Gemmarum cum imaginibus in iisdem insculptis etc. quae a Serenissima Christina Svecorum Regina collectae in Museo Odescalcho adservantur, Romae 1751-52, vol. 2, in fol., fig.

the header? The problem, of course, it that these get really long, and cramming it all into an `h1` could be horrible. Maybe the font on the first line is larger, and then it gets smaller after the first wrap? Is that even possible?

I'm :+1: to merge--that's relatively minor thing we could address in a separate issue if you'd like,

**Comment by axamei** [comment]
@jpstroop I'll play around with the heading on the show page. Let's address that as a separate issue so we can get this on libruby-dev. It's ready for a merge.

**Pull request merged**
